seata:
  enabled: true
  application-id: social-govern-report
  tx-service-group: my_test_tx_group
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 192.9.200.75:8848
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      serverAddr: 192.9.200.75:8848
      group: SEATA_GROUP
      namespace:
      username: "nacos"
      password: "nacos"