server:
  port: 8081
dubbo:
  scan:
    base-packages: com.zeryts.c2c.social.govern.report
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: social-govern-reviewer,social-govern-reward
spring:
  application:
    name: social-govern-report
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.2:8848,192.168.31.2:8847,192.168.31.2:8849
        port: 8081