seata:
  enabled: true
  application-id: social-govern-reviewer
  tx-service-group: social-govern-report
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: ${spring.cloud.nacos.server-addr}
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      serverAddr: ${spring.cloud.nacos.server-addr}
      group: SEATA_GROUP
      namespace:
      username: "nacos"
      password: "nacos"
spring:
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:9999