server:
  port: 8081
dubbo:
  scan:
    base-packages: com.seryts.c2c.servera
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: spring-cloud://localhost
spring:
  application:
    name: demo-dubbo-server-a
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.2:8848
        port: 8081
